# Generated by Django 5.2.4 on 2025-07-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=50, unique=True, verbose_name='Chave de Configuração')),
                ('valor', models.CharField(max_length=200, verbose_name='Valor')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição da Configuração')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
                'ordering': ['chave'],
            },
        ),
    ]
