# Generated by Django 5.2.4 on 2025-07-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_data_demissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='contato',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='contato_emergencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
