# Generated by Django 5.2.4 on 2025-07-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50, unique=True)),
                ('produto', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('andamento', 'Em andamento'), ('finalizado', 'Finalizado'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado')], default='andamento', max_length=20)),
                ('quantidade', models.PositiveIntegerField()),
                ('grade_p', models.PositiveIntegerField(default=0)),
                ('grade_m', models.PositiveIntegerField(default=0)),
                ('grade_g', models.PositiveIntegerField(default=0)),
                ('grade_gg', models.PositiveIntegerField(default=0)),
                ('grade_eg', models.PositiveIntegerField(default=0)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
    ]
