# Generated by Django 5.2.4 on 2025-07-03 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_entrega', models.DateField(verbose_name='Data de Entrega Prevista')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade a Produzir')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('finalizada', 'Finalizada'), ('pendente', 'Pendente'), ('cancelada', 'Cancelada')], default='em_andamento', max_length=20, verbose_name='Status')),
                ('data_finalizacao', models.DateField(blank=True, null=True, verbose_name='Data de Finalização')),
                ('funcionario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_responsaveis', to='funcionarios.funcionario', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Ordem de Produção',
                'verbose_name_plural': 'Ordens de Produção',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
